// 测试
GET http://127.0.0.1:8000
content-type: application/json

###
// 登录接口
POST http://127.0.0.1:8000/login
content-type: application/json

{
    "name":"qcpd的aa1",
    "password":"123"
}

###
// 注册接口
POST http://127.0.0.1:8000/register
content-type: application/json

{
    "name":"qcpd的aa1",
    "password":"123"
}

### 
// 查询文章列表
POST http://127.0.0.1:8000/blog/list
content-type: application/json

{
}


### 
// 查询文章
GET http://127.0.0.1:8000/blog/662337f8aba9770510019082
content-type: application/json

{
}


### 
// 新增文章
POST http://127.0.0.1:8000/blog/add
content-type: application/json

{
    "title": "vue",
    "content": "123222312" 
}

### 
// 编辑文章
POST http://127.0.0.1:8000/blog/put
content-type: application/json

{
    "id":"661b69d15e886a0fb4f1a3b2",
    "title":"react",
    "content":"asd"
}

### 
// 删除文章
POST http://127.0.0.1:8000/blog/delete
content-type: application/json

{
    "id":"6623392ff3c0ad35ccc9a4d1"
}

### 
// 查看浏览量
POST http://127.0.0.1:8000/visit/get
content-type: application/json

{
    "blogId":"test3"
}